spring:
  application:
    name: api_kotlin

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none  # Pode ser "create", "update", "validate" ou "none"
      show-sql: true  # Exibe as queries no console
    properties:
      hibernate:
        default_schema: topic_api
      format_sql: true  # Formata as queries para melhor leitura
      dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    schemas: [public, topic_api]
    create-schema: true
