spring:
  application:
    name: api_kotlin

  datasource:
    url: ${DB_URL:jdbc:postgresql://db-topics.cen8aqaimum6.us-east-1.rds.amazonaws.com:5432/api_kotlin}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Muzambinho-13}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none  # Pode ser "create", "update", "validate" ou "none"
      show-sql: true  # Exibe as queries no console
    properties:
      hibernate:
        default_schema: topic_api
      format_sql: true  # Formata as queries para melhor leitura
      dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    schemas: [public, topic_api]
    create-schema: true

#jdbc:postgresql://db-topics.cen8aqaimum6.us-east-1.rds.amazonaws.com:5432/api_kotlin
#postgres
#Muzambinho-13